### ISSUE TITLE
Sobreescritura del xml de factura al crear cesion

### ISSUE THREAD

**Issue by CarlosToledo1007** [dansanti/l10n_cl_dte_factoring#3]
https://github.com/dansanti/l10n_cl_dte_factoring/blob/d9628fb1f21274caed911f14433a76c1b21e97c5/models/invoice.py#L377

Hola Daniel

He revisado el modulo de factoring y en esa linea produce un problema, ya que sobreescribe el xml de envio al sii y lo sobreescribe localmente (el archivo en disco) y cuando se quiere descargar el xml que se envió al SII, aparece el xml de la cesion y no de la factura

Saludos

**Comment by dansanti** [comment]
si, estaba viendo de que quizas no se guarde más el envío sino que se genere a petición
